name: dotnet package

on: 
  push:
    branches: 
    - main

jobs:
        
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USER }} 
           -p ${{ secrets.DOCKER_PASS }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Publish Docker image
      run: docker push $REPO
  
  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          data: "{ 'myField': 'myFieldValue'}"
